TicTacToe/__init__.py
from flask import Flask
from TicTacToe.config import Config


def create_app(config_file=Config):
    app=Flask(__name__)

    app.config.from_object(Config)
    from TicTacToe.main.routes import main
    from TicTacToe.game.routes import game
    app.register_blueprint(main)
    app.register_blueprint(game)

    return app

TicTacToe/game/__init__.py
#Init file for game

TicTacToe/game/routes.py
from flask import Blueprint,render_template,request,current_app
from random import random,choice
from .geniusplayer import GeniusComputerPlayer
import json
game=Blueprint("game",__name__)

game_move_keeper={}

@game.route("/newgame",methods=['POST','GET'])
def newgame():
    verified=True if request.cookies.get("user",False) else False
    if request.method=="POST":
        mode=int(request.form.get("playmode"))
    return render_template("newgame.html" ,random=random(),mode=mode,verified=verified)

@game.route("/newgame/hardmode",methods=["POST","GET"])
def hardMode():
    if request.method=="POST":
        if(request.is_json):
            user_req=request.get_json()
            user_id=str(user_req["user_id"])
            if(user_req.get("delete_obj",False)):
                try:
                    del(game_move_keeper[user_id])
                    return current_app.response_class(status=200) 
                except KeyError:pass
            else:
                if not(game_move_keeper.get(user_id,False)):
                    game_obj=GeniusComputerPlayer(user_req["letter"],user_req["board"],user_req["available_pos"],user_req["game_tie"])
                    game_move_keeper[user_id]={"game_obj":game_obj}
                    pos={"pos":game_obj.make_move()}

                else:
                    game_obj=game_move_keeper[user_id]["game_obj"]
                    game_obj.board=user_req["board"]
                    game_obj.available_pos=user_req["available_pos"]
                    game_obj.game_tie=user_req["game_tie"]
                    pos={"pos":game_obj.make_move()}

        res=current_app.response_class(response=json.dumps(pos),status=200,mimetype="application/json")
        return res
    
    return current_app.response_class(status=500)       


TicTacToe/main/__init__.py
#Init file for main

TicTacToe/main/routes.py
from flask import Blueprint,render_template,request,current_app
from random import random
main=Blueprint("main",__name__)

@main.route("/")
@main.route("/home")
def home():
    verified=True if request.cookies.get("user",False) else False
    return render_template("index.html" ,random=random(),verified=verified)

@main.route("/newuser",methods=["POST","GET"])
def newUser():
    if request.method=="GET":
        resp=current_app.response_class(status=200)  
        resp.set_cookie("user","true");
        return resp

TicTacToe/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Sofia&display=swap" >
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css')}}?q={{random}}">
    {% block style %}
    {% endblock style %}
    <title>TICTACTOE</title>
</head>
<body>
    <header>
        <a href="{{url_for('main.home')}}" class="back-btn add-negmargin-left"><img src="{{url_for('static',filename='img/back-btn.png')}}" alt="back"/></a>
        <div class="game-name"> Tic Tac Toe</div>
        <div>
            <span class="user-info"></span>
            <span class="img-container">
                <img  src="{{url_for('static',filename='img/any-user.png')}}" alt="user-image">
            </span>
        </div>
    </header>
    <main>
        {% if not verified %}
            <div class="sign-in-container">
                <div class="sign-in">
                    <div class="name">
                        <input id="user-name" name="user-name" type=text maxlength=12  placeholder="User name"  required/>
                        <label for="user-name"></label>
                    </div>
                    <div  class="user-avatar-parent">
                        <span>Choose your avatar:</span>
                        <div class="user-avatar">
                            <span class="transformed-span"><img src="{{url_for('static',filename='img/any-user.png')}}" /></span>
                            <span><img src="{{url_for('static',filename='img/male-user.png')}}"/></span>
                            <span><img src="{{url_for('static',filename='img/female-user.png')}}"/></span>
                        </div>
                    </div>
                    <button type="button"class="signin-btn-unclicked">Register/Sign In</button>
                </div>
            </div>
        {% endif %}
        
        </div>
            {% block content %}
            {% endblock content%}
        </div>

    </main>
    <script type="text/javascript">
        const char_maxlength=12;
        const root=document.querySelector(":root");
        const play_game_btn=document.querySelector(".start-game button[name=play-game]");
        const avatar_select_elements=Array.from(document.querySelectorAll(".user-avatar-parent .user-avatar span"));
        const user_name_tag=document.querySelector("input[name='user-name']");
        const register_signup_btn=document.querySelector(".sign-in-container button[type='button']");
        let base_url="{{request.url}}";
        const full_url=base_url+"newuser";

        // check whether user has registered or not.
        const is_verifed=("{{verified}}".toLowerCase()==="true");
        //Store user name
        let user_name="";

        //Default the avater of user
        let avatar_selected="{{url_for('static',filename='img/any-user.png')}}";

        //show play mode to user
        if(play_game_btn!= null){
            play_game_btn.addEventListener("click",function(e){
            document.querySelector(".play-option").classList.toggle("show-play-option");
        
        });
        }
     
        // Selected user clicked img file as a user avatar.
        avatar_select_elements.forEach((span_ele)=>{
            span_ele.addEventListener("click",function(e){
                avatar_select_elements.forEach((span_ele)=>{
                    span_ele.classList.remove("transformed-span");
                });
                this.classList.add("transformed-span");
                avatar_selected=this.lastElementChild.getAttribute("src");
            });
        });

        //If user has not regitered then ask to enter his/her name.
        if (user_name_tag!=null){
            user_name_tag.addEventListener("keyup",function(e){
            let char_maxlength=parseInt(this.getAttribute("maxlength"));
            if(this.value.length>char_maxlength){
                
                this.value=this.value.substring(0,char_maxlength);
            }
        });
        }


        //If user has not regitered then after clicking register btn register user name to local storage and 
        //tell server that user has been registered to system.
        if( register_signup_btn!=null){
            register_signup_btn.addEventListener("click",function(e){
                this.classList.toggle("signin-btn-clicked");
                if(user_name_tag.value===""){
                    user_name_tag.focus();
                }
                else{
                    fetch(full_url)
                    .then((resp)=>location.reload());
                    let user_data={"user_name":user_name_tag.value,"user_avatar":avatar_selected};
                    localStorage.setItem("user_info",JSON.stringify(user_data));
                    
                }
            });
        }
        function checkUserStatus(){
            if(is_verifed){
                let user_data=JSON.parse(localStorage.getItem("user_info")) || {};
                let user_data_length=Array.from(Object.keys(user_data)).length;
                if(user_data_length!==0){
                    user_name=user_data["user_name"].substring(0,char_maxlength);
                    document.querySelector(".user-info").innerHTML=user_name;
                    document.querySelector(".img-container img").setAttribute("src",user_data["user_avatar"]);
                }

                //Add back btn to home  
                let regx= new RegExp("/newgame","gi")
                if(base_url.match(regx)){
                    document.querySelector(".back-btn").classList.add("remove-negmargin-left");
                }
                else{
                    document.querySelector(".back-btn").classList.remove("remove-negmargin-left");
                }
               
                
            }
        }
        checkUserStatus();
    </script>
    {% block script %}{% endblock script %}
</body>
</html>

TicTacToe/templates/index.html
{% extends 'base.html'%}
{% block content %}
<div class="content">
    <div class="start-game">
        <h3>TICTACTOE</h3>
        <button type=button name="play-game" >Play▶</button>
        <div class="play-option">
            <form action="{{url_for('game.newgame')}}"  method="POST">
                <button type=submit name="playmode" value="0" data-mode="playercomputer">Player v/s Computer</button>
                <button type=submit name="playmode" value="1" data-mode="playerplayer">Player v/s Player(offline)</button>
            </form>
        </div>
    </div>
</div>
{% endblock content%}
{% block script %}
<script>
</script>
{% endblock script %}